### PR TITLE
Upgrade `socket.io` to 4.0.0: 2/3

### PR DESCRIPTION
**Pull request by jyee27**
Deploy https://github.com/iFixit/realtime-notification-server/pull/6 before merging this.

Step 2/3 of upgrading `socket.io`. All of these changes except for 9895809567d9717ecc7b61715953a1fa7290533c are from `socketio/socket.io-client`.

CR
---
7e077a12561522f4e4acfbb8c6f0ad28fc70d195 and 9895809567d9717ecc7b61715953a1fa7290533c are the relevant commits.

7e077a12561522f4e4acfbb8c6f0ad28fc70d195:
* `git remote add upstream git@github.com:socketio/socket.io-client.git`
* `git fetch upstream`
* `git merge upstream/master`

9895809567d9717ecc7b61715953a1fa7290533c:
* Adds a copy of `dist/socket.io.js` to the project root

QA
---
From `iFixit/ifixit`:
* `cd 3P/socket.io-client/`
* `git checkout upgrade-to-version-4-0-0`

Then QA same as steps 2-4 from https://github.com/iFixit/realtime-notification-server/pull/6#issuecomment-803085906.

Connects iFixit/ifixit#32198

### CODE REVIEW

**Comment by andyg0808** [comment]
If I'm understanding what's happening with 9895809, I'd recommend using a symlink instead of a copy. You'll get a much more helpful diff, and it'll probably stay up-to-date if we should end up having to update the `socket.io` version here again.
You'll want to run something like `ln -s socket.io.js dist/socket.io.js` in the project root to create the link.

**Comment by andyg0808** [comment]
deploy_block :+1: on suggestion. Thanks for taking this on; I'm delighted to see us update `socket.io` finally!

**Comment by danielbeardsley** [comment]
Is there still a good reason to have our own fork? Do we know why we currently have our own fork? Does that reasoning still apply?

**Comment by jyee27** [comment]
> Is there still a good reason to have our own fork? Do we know why we currently have our own fork? Does that reasoning still apply?

The only difference from https://github.com/socketio/socket.io-client that I can see is f8efdcf048befa33b0e8ff4621a8785639e1aa2f, which was a bugfix for an issue from 2015 that was fixed in the original repo in 2017. 

I don't see any reason to keep using our fork.

**Comment by danielbeardsley** [comment]
> I don't see any reason to keep using our fork.

Let's try using the upstream npm package instead of our fork and see what happens.

**Comment by danielbeardsley** [comment]
I'm gonna close this in the mean time. We can re-open it later if needed.

**Comment by jyee27** [comment]
> Let's try using the upstream npm package instead of our fork and see what happens.

Seems to work fine. New pull: https://github.com/iFixit/ifixit/pull/36808

**Pull request closed without merging**
